### ISSUE TITLE
ONNX & NNEF Support

### ISSUE THREAD

**Issue by kiritigowda** [kiritigowda/MIVisionX-setup#2]
* Add ONNX Model profile scripts

* Add NNEF Model profile scripts

* Create ONNX & NNEF models list

**Comment by kiritigowda** [comment]
@LakshmiKumar23 & @hansely

**Comment by kiritigowda** [comment]
@LakshmiKumar23 & @hansely any progress on this?

**Comment by LakshmiKumar23** [comment]
@kiritigowda The ONNX support is already added in the profile and generateFullReport scripts

**Comment by hansely** [comment]
It is ready to be merged but I am adding the 0-d tensor support for NNEF.
Will send you the pull request once that is done.

**Comment by hansely** [comment]
Pull request #6 for NNEF support

**Comment by kiritigowda** [comment]
PR #6 will be merged.
